import { Pool, type QueryResult, type QueryResultRow } from 'pg';
import { hashPassword } from './password';
import { categories } from './mock-data';

let pool: Pool | null = null;
let initialized: Promise<void> | null = null;

type TransactionQuery = <Row extends QueryResultRow = QueryResultRow>(
    text: string,
    values?: unknown[]
) => Promise<QueryResult<Row>>;

export function isPostgresEnabled() {
    return Boolean(process.env.DATABASE_URL);
}

function getPool() {
    if (!pool) {
        const connectionString = process.env.DATABASE_URL;
        if (!connectionString) {
            throw new Error('DATABASE_URL is required for Postgres access');
        }

        pool = new Pool({
            connectionString,
            max: 3,
            // Use SSL for Supabase connections
            ssl: connectionString.includes('supabase.co') || connectionString.includes('pooler.supabase.com')
                ? { rejectUnauthorized: false }
                : undefined,
            // Serverless-friendly: close idle connections quickly
            idleTimeoutMillis: 20000,
            connectionTimeoutMillis: 10000,
        });
    }
    return pool;
}

export async function pgQuery<T extends QueryResultRow = QueryResultRow>(text: string, values: unknown[] = []) {
    await initializePostgres();
    await getPool().query('SET search_path TO public');
    return getPool().query<T>(text, values);
}

export async function pgTransaction<T>(callback: (query: TransactionQuery) => Promise<T>) {
    await initializePostgres();
    const client = await getPool().connect();
    const queryInTransaction = <Row extends QueryResultRow = QueryResultRow>(text: string, values: unknown[] = []) => {
        return client.query<Row>(text, values);
    };

    try {
        await client.query('BEGIN');
        await client.query('SET LOCAL search_path TO public');
        const result = await callback(queryInTransaction);
        await client.query('COMMIT');
        return result;
    } catch (error) {
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}

async function initializePostgres() {
    if (!isPostgresEnabled()) return;
    if (!initialized) {
        initialized = initializePostgresSchema();
    }
    return initialized;
}

async function initializePostgresSchema() {
    const db = getPool();

    await db.query('SET search_path TO public');
    await db.query(`
        CREATE TABLE IF NOT EXISTS admin_users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text
        );

        CREATE TABLE IF NOT EXISTS reader_users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            email_verified_at TEXT,
            created_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text,
            updated_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text
        );

        CREATE TABLE IF NOT EXISTS rss_sources (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            feed_url TEXT NOT NULL,
            is_active INTEGER DEFAULT 1,
            last_fetched_at TEXT,
            created_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text
        );

        CREATE TABLE IF NOT EXISTS articles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id BIGINT REFERENCES rss_sources(id),
            source_url TEXT UNIQUE,
            slug TEXT UNIQUE,
            title TEXT NOT NULL,
            summary TEXT DEFAULT '',
            body TEXT DEFAULT '',
            author TEXT DEFAULT '',
            cover_image TEXT DEFAULT '',
            category TEXT DEFAULT '',
            status TEXT DEFAULT 'draft',
            is_featured INTEGER DEFAULT 0,
            publish_date TEXT,
            deleted_at TEXT,
            crawled_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text,
            updated_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text
        );

        CREATE TABLE IF NOT EXISTS categories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE NOT NULL,
            slug TEXT UNIQUE NOT NULL,
            created_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text
        );

        CREATE TABLE IF NOT EXISTS article_comments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
            user_id BIGINT NOT NULL REFERENCES reader_users(id) ON DELETE CASCADE,
            body TEXT NOT NULL,
            quote TEXT DEFAULT '',
            created_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text,
            updated_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text
        );

        CREATE TABLE IF NOT EXISTS schema_migrations (
            name TEXT PRIMARY KEY,
            applied_at TEXT DEFAULT (now() AT TIME ZONE 'utc')::text
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_articles_slug ON articles(slug) WHERE slug IS NOT NULL AND slug != '';
        CREATE UNIQUE INDEX IF NOT EXISTS idx_rss_sources_feed_url ON rss_sources(feed_url);
        CREATE INDEX IF NOT EXISTS idx_article_comments_article_id_created_at ON article_comments(article_id, created_at DESC);
    `);

    await db.query("DELETE FROM articles WHERE status = 'trash' AND deleted_at <= ((now() AT TIME ZONE 'utc') - interval '30 days')::text");
    await db.query("DELETE FROM articles WHERE source_url LIKE 'seed:%'");

    const adminUsername = process.env.ADMIN_USERNAME;
    const adminPassword = process.env.ADMIN_PASSWORD;
    if (adminUsername && adminPassword) {
        if (adminPassword.length < 12) {
            throw new Error('ADMIN_PASSWORD must be at least 12 characters');
        }

        await db.query(
            `
                INSERT INTO admin_users (username, password_hash)
                VALUES ($1, $2)
                ON CONFLICT (username) DO NOTHING
            `,
            [adminUsername, hashPassword(adminPassword)]
        );
    }

    for (const category of categories) {
        await db.query(
            `
                INSERT INTO categories (name, slug)
                VALUES ($1, $2)
                ON CONFLICT (name) DO NOTHING
            `,
            [category.name, category.slug]
        );
    }
}
